import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getClientLedger, getClients } from '../api';
import ErrorMessage from '../components/ErrorMessage';

const fmt = (n) => parseFloat(n).toLocaleString('en-IN', { minimumFractionDigits: 2 });
const fmtDate = (d) => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

const statusColor = {
  pending:              { bg: '#fff8e1', color: '#f57f17' },
  partially_dispatched: { bg: '#e3f2fd', color: '#1565c0' },
  fully_dispatched:     { bg: '#e8f5e9', color: '#2e7d32' },
};

const pill = (text, map) => {
  const s = map[text] || { bg: '#f5f5f5', color: '#555' };
  return (
    <span style={{
      backgroundColor: s.bg, color: s.color,
      padding: '2px 10px', borderRadius: '12px',
      fontSize: '11px', fontWeight: '600',
    }}>
      {text.replace(/_/g, ' ')}
    </span>
  );
};

function printLedger(ledger) {
  const rows = ledger.orders.map((o) => {
    const dispatches = o.dispatch_records.length
      ? o.dispatch_records.map(
          (dr) => `<tr style="background:#f9f9f9"><td colspan="2" style="padding:4px 12px 4px 28px;font-size:12px;color:#555">
            ↳ ${dr.product_name} (${dr.grade}) — ${dr.quantity_dispatched} bags on ${fmtDate(dr.dispatched_at)}
          </td><td colspan="5"></td></tr>`
        ).join('')
      : '';
    return `
      <tr>
        <td>${o.order_code || '-'}</td>
        <td>${o.order_date}</td>
        <td style="text-align:right">${o.quantity_required}</td>
        <td style="text-align:right">${o.dispatched_quantity}</td>
        <td style="text-align:right">₹${fmt(o.price_per_bag)}</td>
        <td style="text-align:right">₹${fmt(o.total_amount)}</td>
        <td>${o.payment_status.toUpperCase()}</td>
      </tr>
      ${dispatches}
    `;
  }).join('');

  const win = window.open('', '_blank');
  win.document.write(`
    <html><head><title>Ledger — ${ledger.client_name}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 32px; color: #222; font-size: 13px; }
      h1 { font-size: 22px; margin-bottom: 4px; }
      .meta { color: #555; font-size: 13px; margin-bottom: 20px; }
      .stats { display: flex; gap: 24px; margin-bottom: 24px; }
      .stat { border: 1px solid #ddd; border-radius: 6px; padding: 10px 16px; min-width: 130px; }
      .stat-label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.8px; }
      .stat-value { font-size: 17px; font-weight: 700; margin-top: 3px; }
      table { width: 100%; border-collapse: collapse; }
      th { background: #f0f0f0; padding: 8px 10px; text-align: left; font-size: 12px; border-bottom: 2px solid #ccc; }
      td { padding: 8px 10px; border-bottom: 1px solid #eee; }
      .footer { margin-top: 32px; color: #aaa; font-size: 11px; }
      @media print { .footer { position: fixed; bottom: 20px; left: 32px; } }
    </style></head><body>
    <h1>${ledger.client_name}</h1>
    <div class="meta">
      Phone: ${ledger.phone}${ledger.address ? ' &nbsp;|&nbsp; Address: ' + ledger.address : ''}
      &nbsp;|&nbsp; Client since: ${fmtDate(ledger.client_since)}
    </div>
    <div class="stats">
      <div class="stat"><div class="stat-label">Total Orders</div><div class="stat-value">${ledger.total_orders}</div></div>
      <div class="stat"><div class="stat-label">Total Value</div><div class="stat-value">₹${fmt(ledger.total_value)}</div></div>
      <div class="stat"><div class="stat-label">Amount Paid</div><div class="stat-value" style="color:#2e7d32">₹${fmt(ledger.total_paid)}</div></div>
      <div class="stat"><div class="stat-label">Outstanding</div><div class="stat-value" style="color:${parseFloat(ledger.outstanding_balance) > 0 ? '#c62828' : '#2e7d32'}">₹${fmt(ledger.outstanding_balance)}</div></div>
    </div>
    <table>
      <thead><tr>
        <th>Order Code</th><th>Date</th><th style="text-align:right">Ordered</th>
        <th style="text-align:right">Dispatched</th><th style="text-align:right">Rate</th>
        <th style="text-align:right">Total</th><th>Payment</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="footer">Generated by SaltFlow &nbsp;|&nbsp; ${new Date().toLocaleString('en-IN')}</div>
    </body></html>
  `);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

const thS = {
  textAlign: 'left', padding: '10px 12px',
  backgroundColor: '#f8f9fa', borderBottom: '2px solid #e0e0e0',
  fontSize: '12px', fontWeight: '600', color: '#555', whiteSpace: 'nowrap',
};
const tdS = { padding: '10px 12px', borderBottom: '1px solid #f0f0f0', fontSize: '13px', color: '#333' };

export default function ClientLedger() {
  const { clientId } = useParams();
  const navigate = useNavigate();

  const [clients, setClients] = useState([]);
  const [selectedId, setSelectedId] = useState(clientId || '');
  const [ledger, setLedger] = useState(null);
  const [expanded, setExpanded] = useState({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    getClients().then(setClients).catch(() => {});
  }, []);

  useEffect(() => {
    if (!selectedId) { setLedger(null); return; }
    setLoading(true);
    setError('');
    setExpanded({});
    getClientLedger(selectedId)
      .then(setLedger)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [selectedId]);

  const handleSelect = (e) => {
    const id = e.target.value;
    setSelectedId(id);
    if (id) navigate(`/ledger/${id}`, { replace: true });
    else navigate('/ledger', { replace: true });
  };

  const toggleExpand = (id) => setExpanded((p) => ({ ...p, [id]: !p[id] }));

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#1a1a1a', margin: 0 }}>Client Ledger</h1>
          <p style={{ color: '#666', marginTop: '4px', marginBottom: 0 }}>
            Complete transaction history for any client
          </p>
        </div>
        {ledger && (
          <button
            onClick={() => printLedger(ledger)}
            style={{
              backgroundColor: '#1a73e8', color: '#fff', border: 'none',
              borderRadius: '6px', padding: '9px 18px', fontSize: '13px',
              fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px',
            }}
          >
            ⬇ Download PDF
          </button>
        )}
      </div>

      {/* Client selector */}
      <div style={{ margin: '20px 0 0', maxWidth: 360 }}>
        <select
          value={selectedId}
          onChange={handleSelect}
          style={{
            width: '100%', padding: '10px 12px', border: '1px solid #ddd',
            borderRadius: '6px', fontSize: '14px', backgroundColor: '#fff',
          }}
        >
          <option value="">— Select a client —</option>
          {clients.map((c) => (
            <option key={c.id} value={c.id}>{c.name} · {c.phone}</option>
          ))}
        </select>
      </div>

      <ErrorMessage message={error} />
      {loading && <p style={{ color: '#888', marginTop: '20px' }}>Loading ledger...</p>}

      {ledger && !loading && (
        <div style={{ marginTop: '24px' }}>

          {/* Client info card */}
          <div style={{
            backgroundColor: '#fff', borderRadius: '8px', padding: '20px 24px',
            boxShadow: '0 1px 4px rgba(0,0,0,0.08)', marginBottom: '20px',
            display: 'flex', flexWrap: 'wrap', gap: '24px', alignItems: 'flex-start',
          }}>
            <div style={{ flex: 1, minWidth: 180 }}>
              <div style={{ fontSize: '11px', color: '#999', textTransform: 'uppercase', letterSpacing: '0.8px' }}>Client</div>
              <div style={{ fontSize: '20px', fontWeight: '700', color: '#1a1a1a', marginTop: '4px' }}>{ledger.client_name}</div>
              <div style={{ fontSize: '13px', color: '#666', marginTop: '2px' }}>{ledger.phone}</div>
              {ledger.address && <div style={{ fontSize: '13px', color: '#888', marginTop: '2px' }}>{ledger.address}</div>}
              <div style={{ fontSize: '12px', color: '#aaa', marginTop: '6px' }}>Client since {fmtDate(ledger.client_since)}</div>
            </div>

            {/* Stats */}
            {[
              { label: 'Total Orders', value: ledger.total_orders, plain: true },
              { label: 'Total Value', value: `₹${fmt(ledger.total_value)}` },
              { label: 'Amount Paid', value: `₹${fmt(ledger.total_paid)}`, green: true },
              {
                label: 'Outstanding',
                value: `₹${fmt(ledger.outstanding_balance)}`,
                red: parseFloat(ledger.outstanding_balance) > 0,
                green: parseFloat(ledger.outstanding_balance) === 0,
              },
            ].map(({ label, value, plain, green, red }) => (
              <div key={label} style={{
                backgroundColor: red ? '#fff3e0' : green ? '#f1f8f1' : '#f8f9fa',
                border: `1px solid ${red ? '#ffcc80' : green ? '#c8e6c9' : '#eee'}`,
                borderRadius: '8px', padding: '14px 20px', minWidth: '130px',
              }}>
                <div style={{ fontSize: '11px', color: '#999', textTransform: 'uppercase', letterSpacing: '0.8px' }}>{label}</div>
                <div style={{
                  fontSize: plain ? '24px' : '18px',
                  fontWeight: '700',
                  color: red ? '#c62828' : green ? '#2e7d32' : '#1a1a1a',
                  marginTop: '6px',
                }}>
                  {value}
                </div>
              </div>
            ))}
          </div>

          {/* Orders table */}
          {ledger.orders.length === 0 ? (
            <div style={{
              textAlign: 'center', padding: '40px', backgroundColor: '#fff',
              borderRadius: '8px', color: '#999', fontSize: '14px',
            }}>
              No orders found for this client.
            </div>
          ) : (
            <div style={{ backgroundColor: '#fff', borderRadius: '8px', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', overflow: 'hidden' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr>
                    <th style={{ ...thS, width: 28 }}></th>
                    <th style={thS}>Order Code</th>
                    <th style={thS}>Date</th>
                    <th style={{ ...thS, textAlign: 'right' }}>Ordered</th>
                    <th style={{ ...thS, textAlign: 'right' }}>Dispatched</th>
                    <th style={{ ...thS, textAlign: 'right' }}>Rate (₹/bag)</th>
                    <th style={{ ...thS, textAlign: 'right' }}>Total (₹)</th>
                    <th style={thS}>Dispatch</th>
                    <th style={thS}>Payment</th>
                  </tr>
                </thead>
                <tbody>
                  {ledger.orders.map((o) => (
                    <>
                      <tr
                        key={o.id}
                        onClick={() => o.dispatch_records.length && toggleExpand(o.id)}
                        style={{ cursor: o.dispatch_records.length ? 'pointer' : 'default' }}
                      >
                        <td style={{ ...tdS, color: '#aaa', fontSize: '11px', textAlign: 'center', paddingRight: 0 }}>
                          {o.dispatch_records.length > 0 ? (expanded[o.id] ? '▾' : '▸') : ''}
                        </td>
                        <td style={{ ...tdS, fontFamily: 'monospace', color: '#1a73e8', fontWeight: '600' }}>
                          {o.order_code || '-'}
                        </td>
                        <td style={tdS}>{o.order_date}</td>
                        <td style={{ ...tdS, textAlign: 'right' }}>{o.quantity_required.toLocaleString()}</td>
                        <td style={{ ...tdS, textAlign: 'right' }}>{o.dispatched_quantity.toLocaleString()}</td>
                        <td style={{ ...tdS, textAlign: 'right' }}>₹{fmt(o.price_per_bag)}</td>
                        <td style={{ ...tdS, textAlign: 'right', fontWeight: '600' }}>₹{fmt(o.total_amount)}</td>
                        <td style={tdS}>{pill(o.status, statusColor)}</td>
                        <td style={tdS}>
                          <span style={{
                            backgroundColor: o.payment_status === 'paid' ? '#e8f5e9' : '#fbe9e7',
                            color: o.payment_status === 'paid' ? '#2e7d32' : '#bf360c',
                            padding: '2px 10px', borderRadius: '12px',
                            fontSize: '11px', fontWeight: '600',
                          }}>
                            {o.payment_status}
                          </span>
                        </td>
                      </tr>

                      {/* Expanded dispatch rows */}
                      {expanded[o.id] && o.dispatch_records.map((dr) => (
                        <tr key={dr.id} style={{ backgroundColor: '#fafbff' }}>
                          <td style={{ ...tdS, borderBottom: 'none' }}></td>
                          <td colSpan={2} style={{ ...tdS, paddingLeft: '24px', color: '#666', fontSize: '12px', borderBottom: 'none' }}>
                            ↳ <span style={{ fontWeight: '600', color: '#333' }}>{dr.product_name}</span>
                            <span style={{ color: '#999', marginLeft: '4px' }}>({dr.grade})</span>
                          </td>
                          <td colSpan={2} style={{ ...tdS, textAlign: 'right', color: '#555', fontSize: '12px', borderBottom: 'none' }}>
                            {dr.quantity_dispatched.toLocaleString()} bags
                          </td>
                          <td colSpan={3} style={{ ...tdS, color: '#999', fontSize: '12px', borderBottom: 'none' }}>
                            {fmtDate(dr.dispatched_at)}
                          </td>
                          <td style={{ ...tdS, borderBottom: 'none' }}></td>
                        </tr>
                      ))}
                    </>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}